let audioCtx=null;
let isFirstStart=true;
let hasWonBlackjack=false;
let isDiscoMode=false;
let luckyBonus=0;
let camera,scene,renderer,controls,objects=[],raycaster;
let moveForward=false,moveBackward=false,moveLeft=false,moveRight=false,canJump=false,isCrouching=false;
let prevTime=performance.now();
const velocity=new THREE.Vector3(),direction=new THREE.Vector3();
let gameState='CORRIDOR',interactTarget=null,activeModal=null;
let wheelMesh,chillWheelMesh,eyeGroup,smileyGroup,isDraggingWheel=false,activeWheelType=null,horrorVelocity=0,chillVelocity=0,isHorrorSpinning=false,isChillSpinning=false,winningGame=null,chillWonGame=null;
let textScreenCtx,textScreenTex,imageScreenCtx,imageScreenTex,lastScreenUpdate=0;
let chillScreenCanvas,chillScreenCtx,chillScreenTex;
let cachedGameImage=new Image();
const eyeTarget=new THREE.Vector3(),eyeJitter=new THREE.Vector3();
let nextJitterTime=0;
let dice1Mesh,dice2Mesh,diceCtx1,diceCtx2,isRollingDice=false;
let secretRoomLight;
let masterVolume=parseFloat(localStorage.getItem('atl_vol'));if(isNaN(masterVolume))masterVolume=0.5;
let userSens=parseFloat(localStorage.getItem('atl_sens'));if(isNaN(userSens))userSens=1.0;
let userFov=parseInt(localStorage.getItem('atl_fov'));if(isNaN(userFov))userFov=75;
let soundEnabled=true;
let headBobTimer=0;
let currentBob=0;
let chillScreens=[],chillWalls=[],chillWallBaseCanvas;
let drawCanvas,drawCtx,drawTexture;
let isDrawing=false,lastDrawUV=null,currentColor='#000';
const paletteColors=['#000','#fff','#f00','#0f0','#00f','#ff0','#0ff','#f0f','#888','#800','#880','#080','#088','#008','#808','#f88'];
let currentNextNode=null;
let deck=[],playerHand=[],dealerHand=[],bjGameOver=false;
let fridgeDoorHinge, ovenDoorHinge;
let isFridgeOpen = false, isOvenOpen = false;
let currentFridgeAngle = 0, currentOvenAngle = 0;
window.forcedHorrorGame = null;
window.forcedChillGame = null;
let _pickerSeq = '';
